=== adeccscholar/BuildEngine-Admin/admin/schemas/security-identities.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:complexType name="securityRepositoryType">
      <xs:attribute name="url" type="xs:anyURI" use="required"/>
      <xs:attribute name="ref" type="xs:string" use="optional"/>
      <xs:attribute name="commit" type="xs:string" use="optional"/>
   </xs:complexType>

   <xs:element name="securityIdentities">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="library" minOccurs="1" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="repository" type="securityRepositoryType"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                  <xs:attribute name="version" type="xs:string" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
         <xs:attribute name="schemaVersion" use="required" fixed="1"/>
      </xs:complexType>
      <xs:unique name="uniqueSecurityLibraryVersion">
         <xs:selector xpath="library"/>
         <xs:field xpath="@id"/>
         <xs:field xpath="@version"/>
      </xs:unique>
   </xs:element>
</xs:schema>

=== adeccscholar/BuildEngine-Admin/admin/security-identities.xml
<?xml version="1.0" encoding="UTF-8"?>
<securityIdentities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="schemas/security-identities.xsd"
                    schemaVersion="1">
   <library id="curl" version="8.21.0">
      <repository url="https://github.com/curl/curl.git" ref="curl-8_21_0"/>
   </library>
   <library id="bzip2" version="1.0.8">
      <repository url="https://sourceware.org/git/bzip2.git"/>
   </library>
   <library id="opengl" version="26.2.1">
      <repository url="https://gitlab.freedesktop.org/mesa/mesa.git" commit="da14d65e4499e66468094be52bff9ea0915a695e"/>
   </library>
   <library id="sqlite" version="3.53.4">
      <repository url="https://github.com/sqlite/sqlite.git" ref="version-{LibraryVersion}"/>
   </library>
   <library id="xerces-c" version="3.3.0">
      <repository url="https://github.com/apache/xerces-c.git" ref="v{LibraryVersion}"/>
   </library>
</securityIdentities>
